const data = [
  {
    id: "1",
    login: { username: "buddy", password: "12345678" },
    name: "Buddy",
    breed: "golden retriever",
    img: "https://images.unsplash.com/photo-1611250282006-4484dd3fba6b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    age: "puppy",
    character: ["active", "likes to fetch sticks", "likes swimming"],
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus leo a tellus aliquet, in mattis turpis pretium. Nunc gravida.",
    friends: [
      {
        id: "4",
        name: "Bella",
        login: { username: "bellla", password: "12345678" },
        breed: "labrador retriever",
        img: "https://images.unsplash.com/photo-1552575595-38bfbd75841a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
        age: "mature",
        character: ["active", "likes swimming"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
      },
      {
        id: "5",
        name: "Winston",
        login: { username: "winston", password: "12345678" },
        breed: "corgi",
        img: "https://images.unsplash.com/photo-1519098901909-b1553a1190af?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8Y29yZ2l8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
        age: "mature",
        character: ["active", "likes to fetch sticks"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
      },
    ],
  },

  {
    id: "2",
    name: "Rex",
    login: { username: "rex", password: "12345678" },
    breed: "german shepherd",
    img: "https://images.unsplash.com/photo-1621951714307-0f9b8070a9b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Z2VybWFuJTIwc2hlcGhlcmR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    age: "senior",
    character: ["passive", "likes to sniff around"],
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dapibus massa a enim auctor molestie. Quisque fringilla id arcu at dictum. In dolor orci, pulvinar vitae placerat a, luctus ut.",
    friends: [
      {
        id: "6",
        name: "Charlie",
        login: { username: "charlie", password: "12345678" },
        breed: "bernese mountain dog",
        img: "https://images.unsplash.com/photo-1628519104175-bf2d5fe7d94d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        age: "mature",
        character: ["passive", "likes to sniff around"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
      },
    ],
  },
  {
    id: "3",
    name: "Jack",
    login: { username: "jack", password: "12345678" },
    breed: "siberian husky",
    img: "https://images.unsplash.com/photo-1605559141066-1549783d18e9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    age: "mature",
    character: ["active", "likes to sniff around"],
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
    friends: [
      {
        id: "4",
        name: "Bella",
        login: { username: "bellla", password: "12345678" },
        breed: "labrador retriever",
        img: "https://images.unsplash.com/photo-1552575595-38bfbd75841a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
        age: "mature",
        character: ["active", "likes swimming"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
      },
    ],
  },
  {
    id: "4",
    name: "Bella",
    login: { username: "bellla", password: "12345678" },
    breed: "labrador retriever",
    img: "https://images.unsplash.com/photo-1552575595-38bfbd75841a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    age: "mature",
    character: ["active", "likes swimming"],
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
    friends: [
      {
        id: "1",
        login: { username: "buddy", password: "12345678" },
        name: "Buddy",
        breed: "golden retriever",
        img: "https://images.unsplash.com/photo-1611250282006-4484dd3fba6b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        age: "puppy",
        character: ["active", "likes to fetch sticks", "likes swimming"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus leo a tellus aliquet, in mattis turpis pretium. Nunc gravida.",
      },
      {
        id: "3",
        name: "Jack",
        login: { username: "jack", password: "12345678" },
        breed: "siberian husky",
        img: "https://images.unsplash.com/photo-1605559141066-1549783d18e9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        age: "mature",
        character: ["active", "likes to sniff around"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
      },
    ],
  },
  {
    id: "5",
    name: "Winston",
    login: { username: "winston", password: "12345678" },
    breed: "corgi",
    img: "https://images.unsplash.com/photo-1519098901909-b1553a1190af?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8Y29yZ2l8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    age: "mature",
    character: ["active", "likes to fetch sticks"],
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
    friends: [
      {
        id: "1",
        login: { username: "buddy", password: "12345678" },
        name: "Buddy",
        breed: "golden retriever",
        img: "https://images.unsplash.com/photo-1611250282006-4484dd3fba6b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        age: "puppy",
        character: ["active", "likes to fetch sticks", "likes swimming"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus leo a tellus aliquet, in mattis turpis pretium. Nunc gravida.",
      },
    ],
  },
  {
    id: "6",
    name: "Charlie",
    login: { username: "charlie", password: "12345678" },
    breed: "bernese mountain dog",
    img: "https://images.unsplash.com/photo-1628519104175-bf2d5fe7d94d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    age: "senior",
    character: ["passive", "likes to sniff around"],
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus elit eget egestas interdum. Maecenas a orci est. Ut in eros eu sem varius pellentesque.",
    friends: [
      {
        id: "2",
        name: "Rex",
        login: { username: "rex", password: "12345678" },
        breed: "german shepherd",
        img: "https://images.unsplash.com/photo-1621951714307-0f9b8070a9b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Z2VybWFuJTIwc2hlcGhlcmR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
        age: "senior",
        character: ["passive", "likes to sniff around"],
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dapibus massa a enim auctor molestie. Quisque fringilla id arcu at dictum. In dolor orci, pulvinar vitae placerat a, luctus ut.",
      },
    ],
  },
];

export default data;
